# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:u8PU2g==,iv:rn8Z1wgVQi4taT7i1roYExHlmBf6rVgCSq3FnYZ2rn8=,tag:yakE88dhw0a5JXMrat8xMA==,type:str]
sops:
  age:
    - recipient: age1e5pludtdqszyz6tz2x2at4ywsc6t4z59laecvs56zu82zc6deysqs8gyw8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L2RPMXdzeTFhWFpReEUz
        WTNPS3BvQ0pnY3ZsQUxONStOSzBGM0VVYnhNCkZIRFE3QnZ5cmRyRVA0Uzl3SWhS
        Z29kTDFsN1ZHUy9NMjNMUDYwanR0ZTQKLS0tIFJMZXFPUlpXMVBTYmxaWjFBUU11
        WFpBMklkV1l5QVVNMmxJWC9zd2dpVHcK2qiGRqfffoivqOSGAoMVP28A5PkVNGQV
        FmXObsezRT9OAAdRxzkwl1O6ESP1OlF+EPWkesQGM/XtLbcWbIg71Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T16:12:25Z"
  mac: ENC[AES256_GCM,data:N+ddCguL+kSRPgqS7AzP9ZoHdNU//5kskeuSVCdPboUiG18mcw8AeVZM0BfDOpIYUVgwKRIo2ZMv7XrTjFfEJsZpjsdRp7ABvl3d+GA98eVv2Bgn4cjvVj/cQF29RKcJYgzYi5EE2kwW8y1rK8Vq5ystbvWgXLjqQ0YNI1Uv5tM=,iv:bm6zzODSrePkCuPeHxKp9V7r4L+oUJ7UdlFbTjff+yk=,tag:0hfvPYh/CJlbcnI7AMSFCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
