# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fpjqwXWjwITRFhfEYGyRX9aRksq2npenFNwYY+MjClU=,iv:ksLlQYi1v+DiWlad6TlQVdzCs840OGG87r6OrzC7S8Y=,tag:HmHmSmHpRjGTVTpbJuhM7w==,type:str]
sops:
  age:
    - recipient: age1e5pludtdqszyz6tz2x2at4ywsc6t4z59laecvs56zu82zc6deysqs8gyw8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWK2FOQVltN0hkU1MwdDBp
        bDV1c3U3SlBIL0tDTzY1QXVORWJmZHRkakJVCmdxVW90ajlFdzlSWGtRN3cvRHVV
        N0FVeGpVSDBrZnhOZE9NU1AwdGpMdkkKLS0tIFVWdzlwdUF3R0tiUmVDd2hKRjAy
        Z1Bhd0NHNWkweUtpTGIvUWc2VUlvYUkKsSns8YSkUE+AnTDiJlM5n6ZBJQNN/h5+
        G/OUIv6M6SvZA1a/dLBOjXgyEUjccRkDPXbU+nKqxLHLArdNqAFswQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T16:12:25Z"
  mac: ENC[AES256_GCM,data:xcA0FijkLuGkpddypUBxHAB5yB7OlmK8dGQxlxl10vUZ556KV4qtGCFCkT9IMbT4Ea3j5d31kE/PyJuSQqQxuTCRgediVL4qKxsm0mlIhfwlbIUMPp5abUKcPUUPxuJKl5DNYScCS3E1ikyX9rWE3ri9pFX5HupE2W4mX+UZ2Uk=,iv:D7mUMUOiQw/kLSEKzBQ489P7l53hW0686nKATC4jz04=,tag:Cz1hnAyAsqNLYv7qyl1JSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
